### ISSUE TITLE
XML validation errors

### ISSUE THREAD

**Issue by following5** [opencaching/gpx-extension#13]
I have created [this](http://following.bplaced.net/caches/OC12A61.gpx) sample GPX file using the [Okapi implementation](https://github.com/opencaching/okapi/pull/511), tweaked the scheme location to `https://raw.githubusercontent.com/opencaching/gpx-extension-v1/feature/initial-elements/schema.xsd` and feeded it to some online validators.

Maybe all the validators used the same backend, at least they all produced similar error messages. All of them complained about one of the child elements of `<oc:cache>`, e.g.

`Cvc-complex-type.2.4.a: Invalid Content Was Found Starting With Element 'oc:trip_time'. One Of '{"https://github.com/opencaching/gpx-extension-v1":other_code}' Is Expected., Line '87', Column '59'.`

or

`Error - Line 88, 59: org.xml.sax.SAXParseException; lineNumber: 88; columnNumber: 59; cvc-complex-type.2.4.a: Invalid content was found starting with element 'oc:trip_time'. One of '{"https://github.com/opencaching/gpx-extension-v1":other_code}' is expected.`

If I reorder the child elements of `oc:cache`, they may complain about an other element! E.g. if I move `oc:trip_time` before `oc:type`, then the first validator says:

`Cvc-complex-type.2.4.a: Invalid Content Was Found Starting With Element 'oc:type'. One Of '{"https://github.com/opencaching/gpx-extension-v1":trip_distance, "https://github.com/opencaching/gpx-extension-v1":requires_password, "https://github.com/opencaching/gpx-extension-v1":other_code}' Is Expected., Line '85', Column '30'.`

Some validators also complain about the first OC element added to each `groundspeak:log`, either the log_uuid or the site_team_entry flag. E.g.

`Cvc-complex-type.2.4.a: Invalid Content Was Found Starting With Element 'oc:site_team_entry'. One Of '{"http://www.groundspeak.com/cache/1/0/1":text, "http://www.groundspeak.com/cache/1/0/1":log_wpt}' Is Expected., Line '71', Column '105'.`

It's only the OC extension they all complain about, not the groundspeak extension. Should I be concerned, or are those validators mad?

**Comment by following5** [comment]
@wrygiel 
Could you have a look at this? It's the only thing left which blocks the release of initial elements.

**Comment by wrygiel** [comment]
Order of elements in `<xs:sequence>` matters. Therefore, validator will not validate the document if the order in your XML file is incorrect.

From your example:

```xml
<oc:cache>
	<oc:type>Event Cache</oc:type>
	<oc:size>Nano</oc:size>
	<oc:requires_password>false</oc:requires_password>
	<oc:trip_time>2.17</oc:trip_time>
	<oc:trip_distance>1.2</oc:trip_distance>
	<oc:other_code>GC7777</oc:other_code>
</oc:cache>
```

But according to [your XSD](https://github.com/opencaching/gpx-extension-v1/blob/cc0ce033499be4ffeefc39a40bab65d382c75c06/schema.xsd#L87), `trip_time` must come before `requires_password`.

**Comment by wrygiel** [comment]
While it is usually not very important for the end client, it is still better to stick to the order when generating your XML. For example, in order to be able to validate it with existing schema validators.

**Comment by wrygiel** [comment]
BTW, if a remember correctly `xs:boolean` allows values such as `0` and `1` too.

**Comment by following5** [comment]
Okay, thanks!

Now there is the problem left with the `oc:log_uuid` or `oc:site_team_entry`. The error message is similar. Obviously this validator does not like that we insert elements into a `groundspeak:log` sequence; it wants to have a `groundspeak:log_wpt` or an additional `groundspeak:text` instead. Those two GS elements are both defined with 0...unbounded occurence.

An alternative would be this:

```
<groundspeak:cache>
    ... GS cache elements ...
    <groundspeak:logs>
        <groundspeak:log id="12345">
            ... GS log elements ...
        </groundspeak:log>
    </groundspeak:logs>
</groundspeak:cache>

<oc:cache>
    ... OC cache elements ...
    <oc:logs>
        <oc:log id="12345">
            <oc:log_uuid>...</oc:log_uuid>
            <oc:site_team_entry>...</oc:site_team_entry>
        </oc:log>
    </oc:logs>
</oc:cache>
```

Then developers would need to combine the GC and OC log elements by IDs.

Duplicating all the log properties into `oc:log` is not an option, that would create too much data volume.

How to proceed? Ignore this validator error? I think all those online validators are based on two different validator tools, and only one of them complained.

**Comment by wrygiel** [comment]
Not sure which option is better. In practice, adding unknown elements to existing schemas won't break anything. However, if none of the other popular extensions "break" existing XML schemas, then I would try to make ours to not break it too.

**Comment by wrygiel** [comment]
> In practice, adding unknown elements to existing schemas won't break anything.

Well, perhaps I should say "won't break 99.9% of apps". There's always a chance that some developer did his validation in a non-forward-compatible way. It's perfectly okay to ignore this 0.1% chance from practical perspective, but in theory, we are "breaking" Groundspeak's elements (because they didn't allow non-Groundspeak elements in their elements). That's way the validators are complaining about it.

Problem is, many developers use such validators. It's hard to judge what they think when they see that OC elements "break their GPX files".

**Comment by wrygiel** [comment]
> However, if none of the other popular extensions "break" existing XML schemas, then I would try to make ours to not break it too.

The point is, to "not be the first one". :) If breaking Groundspeak schema is acceptable in the community, then it's okay to break it.

**Comment by following5** [comment]
Okay. I am fine with moving the log information away from `groundpeak:logs`. This also fits well into the Okapi GPX logic.

**Comment by following5** [comment]
In the existing extensions I did not find any breaks of the Groundspeak schema. GSAK 1.6 defines an element for log images, but that also has a log-ID child element, so I guess it is placed outside of `groundspeak:log`.

**Comment by wrygiel** [comment]
Okay! Sorry, that I cannot help more at this time!

**Comment by following5** [comment]
I think I can complete it on my own now. And I am very grateful about all the help you gave so far. Would have screwed it up worse than Groundspeak if I had made it on my own. ;-)
