### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by andrixnet** [opencaching/gpx-extension#16]
I have opened a documentation section here: https://wiki.opencaching.eu/index.php/Opencaching_GPX_Extension 

gpx-extention developers, with the advent of the initial release, please provide suitable documentation.

**Comment by wrygiel** [comment]
I think that GitHub is a better place for such documentation. In general, documentation should reside with the code (and be committed in unison).

**Comment by andrixnet** [comment]
I understand and fully agree that technical docs should reside at GitHub and be maintained up to date with the code. 

However I believe that the Wiki is an excellent place for interfacing defining information about OC with the world and thus i think a general presentation (that is not the actual technical documentation) of the GPX extension should go to the Wiki, of course, with refences to the up-to-date technical specs.

**Comment by following5** [comment]
done
