### ISSUE TITLE
Topografix 1.1

### ISSUE THREAD

**Issue by Bananeweizen** [opencaching/gpx-extension#2]
TerraCaching.com uses Topografix 1.1. As least that is what 4 of the test cases in the cgeo repository say: https://github.com/cgeo/cgeo/blob/master/tests/res/raw/tc99un_gpx.gpx. Just for the sake of completeness this should be documented, even though it is not an opencaching site.

Your other conclusions are supported well by the cgeo test cases. All of them are Groundspeak 1.0.1, not a single 1.0 or 1.1.

**Comment by tsteven4** [comment]
That link is dead, but one is here today https://github.com/cgeo/cgeo/blob/master/main/src/androidTest/res/raw/terracaching_gpx.gpx
