### ISSUE TITLE
More extensions

### ISSUE THREAD

**Issue by Bananeweizen** [opencaching/gpx-extension#3]
Not sure if you are interested in these, but it might make sense to refer to some other extensions too, depending on what you want to do with the document later:
* GSAK has a multitude of extensions under http://www.gsak.net/xmlv1/1 to http://www.gsak.net/xmlv1/6 (or maybe even more nowadays).
* cgeo has its own extension under http://www.cgeo.org/wptext/1/0 to store additional attributes about waypoints (whether it was visited, whether it is userdefined).

Just skimmed through the cgeo XML parser for these: https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/files/GPXParser.java#L77 and following.

**Comment by wrygiel** [comment]
> GSAK has a multitude of extensions under http://www.gsak.net/xmlv1/1 to http://www.gsak.net/xmlv1/6 (or maybe even more nowadays).

OMG. They have more than one namespace *too*? They seem to follow the same [weird behavior](https://github.com/opencaching/gpx-extension/issues/4) which Topografix and Groundspeak does.

**Comment by wrygiel** [comment]
Added in https://github.com/opencaching/gpx-extension/commit/dee829ab1d82b4fb908abc4c0ca6b866862134b4

**Comment by Bananeweizen** [comment]
I also was not aware that this strategy is bad until you mentioned it. In cgeo we have been able to handle all the extension versions simultaneously by basically registering all combined rules in a single parser.

**Comment by wrygiel** [comment]
> In cgeo we have been able to handle all the extension versions simultaneously by basically registering all combined rules in a single parser.

Yes, I saw that in the code sample you sent us 2 days ago. You have handled the situation correctly, but this is caused by bad (backward-incompatible) schema design. If this continues, then you will also be forced to add new xmlns to your list in the future, once new versions are released, and you shouldn't be forced to do that (that's why it's not backward compatible).
