### ISSUE TITLE
Choosing the namespace

### ISSUE THREAD

**Issue by wrygiel** [opencaching/gpx-extension#6]
In the current draft, the value for our Opencaching extension namespace is `https://github.com/opencaching/gpx-extension/tree/stable-v1`.

However, I'm thinking that perhaps `https://github.com/opencaching/gpx-extension-v1` would be even better. Side effects:

* If we ever planned to release a new major version (`2.x.x`), we would be forced to create a new repository (instead of creating a new `stable-v2` branch). But will we ever? Hopefully not.

* If we include the major version in the name of the repository itself, then we won't need to include it in the branch name. We will be able to stick with the "standard" Git `master` branch.

**Comment by wrygiel** [comment]
> But will we ever? Hopefully not.

(Because releasing new major version [SHOULD](http://semver.org/) break backward compatibility. And we don't want that.)

**Comment by wrygiel** [comment]
We could also skip the major version from the name, and simply use `https://github.com/opencaching/gpx-extension`. We would still probably need a new repository if we ever wanted to break backward-compatibility. Because (once released) `https://github.com/opencaching/gpx-extension` should keep resolving to the most recent of the `1.x.x` versions.

**Comment by following5** [comment]
I have no strong feelings about this, but `https://github.com/opencaching/gpx-extension-v1` looks most appealing to me.
* It's simpler than `https://github.com/opencaching/gpx-extension/tree/stable-v1`.
* It's in the form that people are used to, including a version number.
* In the unlikely case that a new major version is needed, the naming scheme will be consistent.

**Comment by wrygiel** [comment]
Okay, I'll update it so.

**Comment by wrygiel** [comment]
BTW - We are resigning from the `stable-v1` / `master` approach. This means that the `master` will not contain the **stable** version of the extension. So it needs a bit more protection - we shouldn't commit to `master` before we're 100% sure it's correct, etc.

Perhaps I will make a clean master then, and move the current proposals to a separate branch?
